import type { LanguageConfig } from "../types";

export const esCoConfig: LanguageConfig = {
  code: "en-es-CO",
  sourceLanguage: "en",
  targetLanguage: "es",
  targetRegion: "CO",
  targetLocale: "es-CO",
  displayName: "Colombian Spanish",
  nativeName: "Espanol Colombiano",
  flag: "\uD83C\uDDE8\uD83C\uDDF4",
  available: true,

  ui: {
    tabTalk: "HABLAR",
    tabPatterns: "PATRONES",
    tabMissions: "MISIONES",
    tabVocab: "VOCAB",
    tabProgress: "PROGRESO",
    levelNames: ["Principiante", "Basico", "Intermedio", "Avanzado", "Fluido"],
    startPrompt: "Escribe o habla en espanol...",
    correctLabel: "Sin errores",
    errorLabel: "Correccion",
    readyMessage: "Listo para practicar?",
  },

  personas: [
    {
      id: "carlos",
      name: "Carlos",
      age: 28,
      role: "Street vendor, Medellin",
      setting: "Bus stop on a rainy afternoon",
      personality: "Friendly, uses paisa slang, loves football and arepas",
      systemPrompt: `You are Carlos, a 28-year-old street vendor in Medellin, Colombia. You sell empanadas and jugo de lulo near the metro station. You're friendly, use paisa slang (parcero, que mas, pues), and love talking about Atletico Nacional and your mom's cooking. You're waiting at a bus stop and struck up a conversation with a foreigner who's learning Spanish. Be warm, patient, and natural. Use Colombian expressions but explain them when you notice confusion. Keep it casual.`,
      accentColor: "#f97316",
      avatar: "\uD83D\uDC68\u200D\uD83C\uDF73",
      difficulty: 1,
      tags: ["casual", "slang", "street", "paisa"],
      fallbackResponses: [
        "Ey parcero, que mas pues? Como va todo?",
        "Jaja, eso esta bien! Usted aprende rapido.",
        "Hmm, no le entendi bien, pero tranquilo, volvamos a intentar.",
        "Oiga, quiere una empanada? Las de mi mama son las mejores.",
        "Bueno parce, sigamos hablando que asi se aprende!",
      ],
      difficultyModifiers: {
        beginner: "Use simple vocabulary. Speak slowly. Avoid complex slang. Explain any Colombian expression you use in parentheses.",
        intermediate: "Use natural Colombian slang occasionally (parcero, que mas, chimba). Don't explain every word unless they seem confused.",
        advanced: "Speak at full natural paisa speed with idioms, slang, and local references. Challenge them with complex sentences.",
      },
    },
    {
      id: "alejandra",
      name: "Alejandra",
      age: 34,
      role: "Hotel receptionist, Cartagena",
      setting: "Front desk of a boutique hotel in the Old City",
      personality: "Professional yet warm, costena accent, loves history and food recommendations",
      systemPrompt: `You are Alejandra, a 34-year-old hotel receptionist at a boutique hotel in Cartagena's Old City. You're professional but warm (costena hospitality), know everything about local restaurants, history, and hidden gems. You use costena expressions (ombe, erda, ajá) but can switch to more formal Spanish when needed. A guest is practicing their Spanish with you. Be encouraging, correct gently, and share local knowledge.`,
      accentColor: "#3b82f6",
      avatar: "\uD83D\uDC69\u200D\uD83D\uDCBC",
      difficulty: 2,
      tags: ["professional", "hospitality", "costena", "cartagena"],
      fallbackResponses: [
        "Bienvenido! En que le puedo ayudar?",
        "Ay que bien habla espanol! Siga asi.",
        "Ombe, le recomiendo que visite el Castillo de San Felipe manana temprano.",
        "No se preocupe, aqui estamos para ayudarle con lo que necesite.",
        "Le puedo recomendar un restaurante buenisimo en Getsemani?",
      ],
      difficultyModifiers: {
        beginner: "Speak in simple professional Spanish. Use polite forms (usted). Explain any local reference. Keep sentences short.",
        intermediate: "Mix formal and casual naturally. Use some costena expressions. Give real recommendations with detail.",
        advanced: "Full costena natural speech with idioms. Discuss history and culture at depth. Use subjunctive and complex structures.",
      },
    },
    {
      id: "sofia_tutor",
      name: "Sofia",
      age: 26,
      role: "University Spanish tutor, Bogota",
      setting: "Coffee shop near Universidad Nacional",
      personality: "Patient, academic, explains grammar clearly, uses rolo accent",
      systemPrompt: `You are Sofia, a 26-year-old Spanish language tutor who studies linguistics at Universidad Nacional in Bogota. You meet students at a coffee shop to practice. You're patient, use the neutral rolo (Bogota) accent, and love explaining why things work in Spanish. You gently correct errors and offer alternative ways to express the same idea. You enjoy discussing music, literature, and Colombian politics.`,
      accentColor: "#8b5cf6",
      avatar: "\uD83D\uDC69\u200D\uD83C\uDF93",
      difficulty: 2,
      tags: ["academic", "grammar", "bogota", "rolo"],
      fallbackResponses: [
        "Hola! Listo para practicar? Pidamos un tinto primero.",
        "Mmm interesante como dijiste eso. Hay otra forma tambien...",
        "Muy bien! Tu pronunciacion esta mejorando mucho.",
        "Sabes que? Eso me recuerda una regla gramatical interesante.",
        "Tranquilo, equivocarse es parte del proceso. Intentemos de nuevo.",
      ],
      difficultyModifiers: {
        beginner: "Explain grammar in English when needed. Give simple examples. Celebrate small wins. Use present tense mostly.",
        intermediate: "Stay mostly in Spanish. Introduce subjunctive and conditional. Reference grammar patterns by name.",
        advanced: "Speak only in Spanish. Discuss complex topics. Challenge with subjunctive, conditional perfect, and literary references.",
      },
    },
    {
      id: "diego",
      name: "Diego",
      age: 42,
      role: "Taxi driver, Bogota",
      setting: "Driving through Bogota traffic on a Tuesday morning",
      personality: "Talkative, opinionated, knows all the shortcuts and gossip",
      systemPrompt: `You are Diego, a 42-year-old taxi driver in Bogota. You've been driving for 15 years and know every shortcut in the city. You're talkative, opinionated about politics and football, and love giving unsolicited life advice. You use casual bogotano Spanish with lots of filler words (pues, o sea, digamos). A tourist got in your cab and is trying to practice Spanish. Engage naturally.`,
      accentColor: "#10b981",
      avatar: "\uD83D\uDE95",
      difficulty: 3,
      tags: ["casual", "fast", "bogota", "transport"],
      fallbackResponses: [
        "Pa donde vamos? Hay un trancón terrible por la septima.",
        "Uy hermano, usted si habla bien! De donde es?",
        "Sabe que? Este pais esta loco pero uno lo quiere.",
        "Mire, yo le digo una cosa — la vida es corta, disfrútela.",
        "Jajaja eso estuvo bueno. Vamos bien, ya casi llegamos.",
      ],
      difficultyModifiers: {
        beginner: "Slow down. Use simple directions. Ask yes/no questions. Explain slang you use.",
        intermediate: "Natural speed with some filler words. Share opinions. Use indirect speech.",
        advanced: "Full speed bogotano with rapid-fire opinions, interruptions, and complex narrative. Don't wait for them to respond fully.",
      },
    },
  ],

  grammarPatterns: [
    {
      id: "ser_estar",
      title: "Ser vs Estar",
      formula: "SER = identity/permanent | ESTAR = state/temporary",
      shortExplanation: "Ser for who you ARE, Estar for how you FEEL or where you ARE right now",
      fullExplanation: "Ser describes inherent qualities, identity, origin, time, and permanent characteristics. Estar describes temporary states, locations, emotions, and conditions that can change.",
      examples: [
        { target: "Yo soy colombiano", source: "I am Colombian", isCorrect: true, explanation: "Identity/nationality = SER", audioText: "Yo soy colombiano" },
        { target: "Estoy cansado", source: "I am tired", isCorrect: true, explanation: "Temporary state = ESTAR", audioText: "Estoy cansado" },
        { target: "Soy cansado", source: "I am tired (WRONG)", isCorrect: false, explanation: "Tired is temporary → use ESTAR not SER", audioText: "Soy cansado" },
        { target: "La fiesta es en mi casa", source: "The party is at my house", isCorrect: true, explanation: "Events use SER for location", audioText: "La fiesta es en mi casa" },
        { target: "Ella esta bonita hoy", source: "She looks pretty today", isCorrect: true, explanation: "Temporary appearance = ESTAR", audioText: "Ella está bonita hoy" },
      ],
      drillPrompt: "Create sentences where the user must choose between ser and estar. Mix identity vs temporary state scenarios.",
      commonErrors: ["Using 'soy' for emotions", "Using 'estoy' for nationality", "Confusing event locations"],
      linkedPersonaIds: ["carlos", "sofia_tutor"],
      difficulty: 1,
    },
    {
      id: "preterite_imperfect",
      title: "Preterite vs Imperfect",
      formula: "Preterite = completed action | Imperfect = ongoing/habitual past",
      shortExplanation: "Did it happen once? Preterite. Was it ongoing? Imperfect.",
      fullExplanation: "Preterite (preterito indefinido) describes completed past actions with clear beginning/end. Imperfect (preterito imperfecto) describes habitual past actions, descriptions, ongoing states, and background information in narratives.",
      examples: [
        { target: "Ayer fui al mercado", source: "Yesterday I went to the market", isCorrect: true, explanation: "Completed action with specific time = preterite", audioText: "Ayer fui al mercado" },
        { target: "De niño iba al parque", source: "As a child I used to go to the park", isCorrect: true, explanation: "Habitual past action = imperfect", audioText: "De niño iba al parque" },
        { target: "Llovia cuando sali", source: "It was raining when I left", isCorrect: true, explanation: "Background (imperfect) + interruption (preterite)", audioText: "Llovía cuando salí" },
        { target: "Ayer llovía todo el dia", source: "Yesterday it rained all day (WRONG)", isCorrect: false, explanation: "Specific completed timeframe = preterite: 'llovió'", audioText: "Ayer llovía todo el día" },
        { target: "Cuando tenia 10 años vivia en Bogota", source: "When I was 10 I lived in Bogota", isCorrect: true, explanation: "Age + ongoing state = both imperfect", audioText: "Cuando tenía diez años vivía en Bogotá" },
      ],
      drillPrompt: "Create narrative scenarios mixing preterite and imperfect. Ask the user to describe past events and habitual actions.",
      commonErrors: ["Using preterite for habitual actions", "Using imperfect for completed events", "Mixing them in narration"],
      linkedPersonaIds: ["diego", "alejandra"],
      difficulty: 2,
    },
    {
      id: "subjunctive_basic",
      title: "Subjunctive (Basic)",
      formula: "WEIRDO triggers: Wishes, Emotions, Impersonal, Recommendations, Doubt, Ojalá",
      shortExplanation: "Use subjunctive after expressions of desire, doubt, or emotion about another person's actions",
      fullExplanation: "The subjunctive mood is triggered by expressions of wishes (querer que), emotions (me alegra que), impersonal expressions (es importante que), recommendations (recomendar que), doubt (dudar que), and ojalá. It's used in the subordinate clause when the subject changes.",
      examples: [
        { target: "Quiero que vengas", source: "I want you to come", isCorrect: true, explanation: "Wish + different subject = subjunctive", audioText: "Quiero que vengas" },
        { target: "Espero que estes bien", source: "I hope you're well", isCorrect: true, explanation: "Emotion/wish about someone else = subjunctive", audioText: "Espero que estés bien" },
        { target: "Quiero que vienes", source: "I want you to come (WRONG)", isCorrect: false, explanation: "After 'quiero que' → subjunctive 'vengas' not indicative 'vienes'", audioText: "Quiero que vienes" },
        { target: "Es importante que estudies", source: "It's important that you study", isCorrect: true, explanation: "Impersonal expression + que = subjunctive", audioText: "Es importante que estudies" },
        { target: "No creo que sea verdad", source: "I don't think it's true", isCorrect: true, explanation: "Doubt/negation + que = subjunctive", audioText: "No creo que sea verdad" },
      ],
      drillPrompt: "Present scenarios requiring subjunctive: wishes about others, emotional reactions, recommendations. Mix correct and incorrect usage.",
      commonErrors: ["Using indicative after 'quiero que'", "Forgetting subjunctive with 'espero que'", "Using subjunctive with same-subject (should use infinitive)"],
      linkedPersonaIds: ["sofia_tutor"],
      difficulty: 3,
    },
  ],

  missions: [
    {
      id: "week1_greetings",
      week: 1,
      title: "First Impressions",
      description: "Master Colombian greetings and small talk",
      difficulty: 1,
      estimatedMinutes: 5,
      keyPhrases: [
        { phrase: "Que mas?", translation: "What's up?", phonetic: "keh mahs", audioText: "Que más" },
        { phrase: "Todo bien, gracias", translation: "All good, thanks", phonetic: "toh-doh bee-en", audioText: "Todo bien, gracias" },
        { phrase: "Mucho gusto", translation: "Nice to meet you", phonetic: "moo-cho goos-toh", audioText: "Mucho gusto" },
        { phrase: "De donde eres?", translation: "Where are you from?", phonetic: "deh don-deh eh-res", audioText: "De dónde eres" },
        { phrase: "Que haces por aqui?", translation: "What are you doing around here?", phonetic: "keh ah-sehs por ah-kee", audioText: "Qué haces por aquí" },
      ],
      linkedPersonaId: "carlos",
      successCriteria: "Complete a natural greeting exchange with Carlos",
      culturalContext: "In Colombia, asking 'que mas?' is the universal casual greeting, similar to 'what's up' but used by everyone.",
    },
    {
      id: "week1_taxi",
      week: 1,
      title: "Taxi Ride",
      description: "Navigate a taxi ride in Bogota — directions, small talk, payment",
      difficulty: 2,
      estimatedMinutes: 8,
      keyPhrases: [
        { phrase: "Lleveme a...", translation: "Take me to...", phonetic: "yeh-veh-meh ah", audioText: "Lléveme a" },
        { phrase: "Cuanto vale?", translation: "How much?", phonetic: "kwahn-toh vah-leh", audioText: "Cuánto vale" },
        { phrase: "Pare aqui, por favor", translation: "Stop here, please", phonetic: "pah-reh ah-kee", audioText: "Pare aquí por favor" },
        { phrase: "Tiene cambio?", translation: "Do you have change?", phonetic: "tee-eh-neh kahm-bee-oh", audioText: "Tiene cambio" },
        { phrase: "Hay mucho trafico", translation: "There's a lot of traffic", phonetic: "eye moo-cho trah-fee-koh", audioText: "Hay mucho tráfico" },
        { phrase: "Por donde queda?", translation: "Which way is it?", phonetic: "por don-deh keh-dah", audioText: "Por dónde queda" },
      ],
      linkedPersonaId: "diego",
      successCriteria: "Complete a full taxi conversation: destination, route discussion, payment",
      culturalContext: "In Colombian taxis, you negotiate or confirm the meter (taximetro). Always ask 'cuanto vale?' before getting in outside the city center.",
    },
    {
      id: "week2_hotel",
      week: 2,
      title: "Hotel Check-in",
      description: "Check into a hotel — requests, questions, recommendations",
      difficulty: 2,
      estimatedMinutes: 8,
      keyPhrases: [
        { phrase: "Tengo una reserva a nombre de...", translation: "I have a reservation under...", phonetic: "ten-go oo-nah reh-ser-vah", audioText: "Tengo una reserva a nombre de" },
        { phrase: "Hasta cuando es la estadia?", translation: "How long is the stay?", phonetic: "ahs-tah kwahn-doh", audioText: "Hasta cuándo es la estadía" },
        { phrase: "A que hora es el desayuno?", translation: "What time is breakfast?", phonetic: "ah keh oh-rah", audioText: "A qué hora es el desayuno" },
        { phrase: "Me puede recomendar un restaurante?", translation: "Can you recommend a restaurant?", phonetic: "meh pweh-deh reh-koh-men-dar", audioText: "Me puede recomendar un restaurante" },
        { phrase: "Necesito una toalla extra", translation: "I need an extra towel", phonetic: "neh-seh-see-toh", audioText: "Necesito una toalla extra" },
      ],
      linkedPersonaId: "alejandra",
      successCriteria: "Complete hotel check-in and get a restaurant recommendation",
      culturalContext: "Colombian hospitality is very warm. Hotel staff often go above and beyond with recommendations and personal touches.",
    },
    {
      id: "week3_grammar_drill",
      week: 3,
      title: "Grammar Bootcamp",
      description: "Practice ser/estar and past tenses with Sofia",
      difficulty: 3,
      estimatedMinutes: 10,
      keyPhrases: [
        { phrase: "Cual es la diferencia?", translation: "What's the difference?", phonetic: "kwahl ehs lah dee-feh-ren-see-ah", audioText: "Cuál es la diferencia" },
        { phrase: "Dame otro ejemplo", translation: "Give me another example", phonetic: "dah-meh oh-troh", audioText: "Dame otro ejemplo" },
        { phrase: "No estoy seguro/a", translation: "I'm not sure", phonetic: "noh ehs-toy seh-goo-roh", audioText: "No estoy seguro" },
        { phrase: "Puedes repetir?", translation: "Can you repeat?", phonetic: "pweh-dehs reh-peh-teer", audioText: "Puedes repetir" },
        { phrase: "Ahora entiendo", translation: "Now I understand", phonetic: "ah-oh-rah en-tee-en-doh", audioText: "Ahora entiendo" },
      ],
      linkedPersonaId: "sofia_tutor",
      successCriteria: "Successfully use ser/estar and preterite/imperfect correctly 3 times each",
      culturalContext: "Colombians appreciate when foreigners make the effort to use correct grammar, especially the formal usted form.",
    },
  ],

  quickPhrases: {
    carlos: ["Ey parcero, que mas?", "Todo bien?", "Me regala una empanada", "Que equipo le va?"],
    alejandra: ["Buenas tardes", "Tengo una reserva", "Que me recomienda?", "Donde queda...?"],
    sofia_tutor: ["Hola profe", "No entendi", "Puedes explicar otra vez?", "Tengo una pregunta"],
    diego: ["Buenas, para donde va?", "Hay mucho trafico hoy?", "Cuanto vale hasta...?", "Pare en la esquina"],
  },

  culturalNotes: [
    { id: "cn1", trigger: "hora|tiempo|tarde|temprano", tip: "Social events start 30-60 min late in Colombia", category: "time", urgency: "soon", contexts: ["carlos", "alejandra"] },
    { id: "cn2", trigger: "cuenta|pagar|dinero|plata", tip: "The inviter usually pays in Colombia", category: "money", urgency: "now", contexts: ["alejandra"] },
    { id: "cn3", trigger: "parcero|parce|llave", tip: "'Parcero' means close friend/bro in paisa slang", category: "social", urgency: "soon", contexts: ["carlos"] },
    { id: "cn4", trigger: "usted|tu|vos", tip: "Colombians often use 'usted' even with friends — it's not always formal", category: "etiquette", urgency: "soon", contexts: ["sofia_tutor", "diego"] },
  ],

  emergencyPhrases: [
    { id: "ep1", category: "emergency", source: "Help!", target: "Ayuda!", phonetic: "ah-yoo-dah", audioText: "Ayuda", urgencyLevel: 3 },
    { id: "ep2", category: "emergency", source: "Call the police", target: "Llame a la policia", phonetic: "yah-meh ah lah poh-lee-see-ah", audioText: "Llame a la policía", urgencyLevel: 3 },
    { id: "ep3", category: "medical", source: "I need a doctor", target: "Necesito un doctor", phonetic: "neh-seh-see-toh oon dok-tor", audioText: "Necesito un doctor", urgencyLevel: 3 },
    { id: "ep4", category: "safety", source: "I'm lost", target: "Estoy perdido", phonetic: "ehs-toy per-dee-doh", audioText: "Estoy perdido", urgencyLevel: 2 },
    { id: "ep5", category: "transport", source: "Stop here please", target: "Pare aqui por favor", phonetic: "pah-reh ah-kee", audioText: "Pare aquí por favor", urgencyLevel: 1 },
    { id: "ep6", category: "food", source: "I'm allergic to...", target: "Soy alergico a...", phonetic: "soy ah-ler-hee-koh", audioText: "Soy alérgico a", urgencyLevel: 2 },
    { id: "ep7", category: "hotel", source: "Where is the bathroom?", target: "Donde esta el bano?", phonetic: "don-deh ehs-tah el bah-nyoh", audioText: "Dónde está el baño", urgencyLevel: 1 },
    { id: "ep8", category: "money", source: "How much does it cost?", target: "Cuanto cuesta?", phonetic: "kwahn-toh kwes-tah", audioText: "Cuánto cuesta", urgencyLevel: 1 },
  ],
};
