import type { Metadata, Viewport } from "next";
import "./globals.css";
import AppShell from "./components/AppShell";

export const metadata: Metadata = {
  title: "Voxxo — Your Voice. Any Language. Instantly.",
  description:
    "AI-powered real-time voice translation for real conversations. Type, voice, face-to-face, video calls, and proximity connect. 12 languages. Zero awkwardness.",
  manifest: "/manifest.json",
  applicationName: "Voxxo",
  keywords: [
    "translation",
    "voice translation",
    "real-time translation",
    "video call",
    "English Spanish",
    "translator",
    "language",
    "communication",
    "traduccion",
    "traductor",
    "traduccion en vivo",
    "videollamada",
    "ingles espanol",
    "traduccion de voz",
    "travel translator",
    "dating translation",
  ],
  authors: [{ name: "MachineMind", url: "https://machinemindconsulting.com" }],
  creator: "MachineMind",
  publisher: "MachineMind",
  formatDetection: {
    telephone: false,
  },
  metadataBase: new URL("https://voxlink-v14.vercel.app"),
  alternates: {
    canonical: "/",
  },
  openGraph: {
    type: "website",
    locale: "en_US",
    alternateLocale: "es_ES",
    url: "https://voxlink-v14.vercel.app",
    title: "Voxxo — Your Voice. Any Language. Instantly.",
    description:
      "AI-powered real-time voice translation. Type, voice, face-to-face, video calls, proximity connect. 12 languages.",
    siteName: "Voxxo",
    // Images auto-generated by opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: "Voxxo — Your Voice. Any Language. Instantly.",
    description:
      "AI voice translation for real conversations. 12 languages. Zero awkwardness.",
    creator: "@voxxoapp",
    // Images auto-generated by twitter-image.tsx
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  icons: {
    icon: [
      { url: "/icons/icon-32.png", sizes: "32x32", type: "image/png" },
      { url: "/icons/icon-192.png", sizes: "192x192", type: "image/png" },
    ],
    shortcut: "/favicon.ico",
    apple: [
      { url: "/icons/apple-icon-180.png", sizes: "180x180", type: "image/png" },
    ],
    other: [
      {
        rel: "mask-icon",
        url: "/icons/safari-pinned-tab.svg",
        color: "#06b6d4",
      },
    ],
  },
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent",
    title: "Voxxo",
  },
  // verification: { google: 'ADD_REAL_CODE_HERE' },
  category: "communication",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  viewportFit: "cover",
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#00DBA8" },
    { media: "(prefers-color-scheme: dark)", color: "#0A0E14" },
  ],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        {/* PWA & Mobile */}
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta
          name="apple-mobile-web-app-status-bar-style"
          content="black-translucent"
        />
        <meta name="apple-mobile-web-app-title" content="Voxxo" />

        {/* Microsoft */}
        <meta name="msapplication-TileColor" content="#0a0a0f" />
        <meta name="msapplication-tap-highlight" content="no" />

        {/* Preconnect for performance */}
        <link rel="preconnect" href="https://0.peerjs.com" />
        <link rel="dns-prefetch" href="https://0.peerjs.com" />

        {/* Google Fonts - Voxxo Brand Typography */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Syne:wght@400;500;600;700;800&family=DM+Sans:ital,opsz,wght@0,9..40,400;0,9..40,500;0,9..40,600;0,9..40,700;1,9..40,400&family=JetBrains+Mono:wght@400;500;600&display=swap"
          rel="stylesheet"
        />

        {/* Favicon fallbacks */}
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/icons/icon-32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/icons/icon-16.png"
        />
        <link rel="apple-touch-icon" href="/icons/apple-icon-180.png" />
      </head>
      <body className="safe-top safe-bottom overscroll-none">
        <AppShell>{children}</AppShell>
      </body>
    </html>
  );
}
